//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinding.AlgorithmLib.Core.Realizations.Algorithms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pathfinding.AlgorithmLib.Core.Realizations.Algorithms.Localization.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A* algorithm.
        /// </summary>
        public static string AStartAlgorithm {
            get {
                return ResourceManager.GetString("AStartAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A* lee algorithm.
        /// </summary>
        public static string AStartLeeAlgorithm {
            get {
                return ResourceManager.GetString("AStartLeeAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost greedy algorithm.
        /// </summary>
        public static string CostGreedyAlgorithm {
            get {
                return ResourceManager.GetString("CostGreedyAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth first algorithm.
        /// </summary>
        public static string DepthFirstAlgorithm {
            get {
                return ResourceManager.GetString("DepthFirstAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijkstra&apos;s algorithm.
        /// </summary>
        public static string DijkstraAlgorithm {
            get {
                return ResourceManager.GetString("DijkstraAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance first algorithm.
        /// </summary>
        public static string DistanceFirstAlgorithm {
            get {
                return ResourceManager.GetString("DistanceFirstAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost greedy (heuristic).
        /// </summary>
        public static string HeuristicCostGreedyAlgorithm {
            get {
                return ResourceManager.GetString("HeuristicCostGreedyAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDA* algorithm.
        /// </summary>
        public static string IDAStarAlgorithm {
            get {
                return ResourceManager.GetString("IDAStarAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lee algorithm.
        /// </summary>
        public static string LeeAlgorithm {
            get {
                return ResourceManager.GetString("LeeAlgorithm", resourceCulture);
            }
        }
    }
}
