//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinding.App.Console.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pathfinding.App.Console.Localization.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose algorithm: .
        /// </summary>
        public static string AlgorithmChoiceMsg {
            get {
                return ResourceManager.GetString("AlgorithmChoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply history.
        /// </summary>
        public static string ApplyHistory {
            get {
                return ResourceManager.GetString("ApplyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply history recording {0}?: .
        /// </summary>
        public static string ApplyHistoryMsg {
            get {
                return ResourceManager.GetString("ApplyHistoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply pathfinding statistics.
        /// </summary>
        public static string ApplyStatistics {
            get {
                return ResourceManager.GetString("ApplyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply statistics {0}?: .
        /// </summary>
        public static string ApplyStatisticsMsg {
            get {
                return ResourceManager.GetString("ApplyStatisticsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply pathfinding visualization.
        /// </summary>
        public static string ApplyVisualization {
            get {
                return ResourceManager.GetString("ApplyVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply visualization {0}?: .
        /// </summary>
        public static string ApplyVisualizationMsg {
            get {
                return ResourceManager.GetString("ApplyVisualizationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble graph.
        /// </summary>
        public static string AssembleGraph {
            get {
                return ResourceManager.GetString("AssembleGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad value input. Try again: .
        /// </summary>
        public static string BadInputMsg {
            get {
                return ResourceManager.GetString("BadInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change cost.
        /// </summary>
        public static string ChangeCost {
            get {
                return ResourceManager.GetString("ChangeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change graph colors.
        /// </summary>
        public static string ChangeGraphColors {
            get {
                return ResourceManager.GetString("ChangeGraphColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change path colors.
        /// </summary>
        public static string ChangePathColors {
            get {
                return ResourceManager.GetString("ChangePathColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change pathfinding colors.
        /// </summary>
        public static string ChangePathfindingColors {
            get {
                return ResourceManager.GetString("ChangePathfindingColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change range colors.
        /// </summary>
        public static string ChangeRangeColors {
            get {
                return ResourceManager.GetString("ChangeRangeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color: .
        /// </summary>
        public static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose graph assemble.
        /// </summary>
        public static string ChooseGraphAssemble {
            get {
                return ResourceManager.GetString("ChooseGraphAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear vertices colors.
        /// </summary>
        public static string ClearColors {
            get {
                return ResourceManager.GetString("ClearColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear graph.
        /// </summary>
        public static string ClearGraph {
            get {
                return ResourceManager.GetString("ClearGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear history.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear pathfinding range.
        /// </summary>
        public static string ClearPathfindingRange {
            get {
                return ResourceManager.GetString("ClearPathfindingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string ColorsUnitMenuItem {
            get {
                return ResourceManager.GetString("ColorsUnitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomSmoothLevel {
            get {
                return ResourceManager.GetString("CustomSmoothLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark blue.
        /// </summary>
        public static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark cyan.
        /// </summary>
        public static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark gray.
        /// </summary>
        public static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark green.
        /// </summary>
        public static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark magenta.
        /// </summary>
        public static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark red.
        /// </summary>
        public static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark yellow.
        /// </summary>
        public static string DarkYellow {
            get {
                return ResourceManager.GetString("DarkYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input animation speed delay time (milliseconds): .
        /// </summary>
        public static string DelayTimeInputMsg {
            get {
                return ResourceManager.GetString("DelayTimeInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter animation delay.
        /// </summary>
        public static string EnterAnimationDelay {
            get {
                return ResourceManager.GetString("EnterAnimationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pathfinding range.
        /// </summary>
        public static string EnterPathfindingRange {
            get {
                return ResourceManager.GetString("EnterPathfindingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit {0}?: .
        /// </summary>
        public static string ExitMsg {
            get {
                return ResourceManager.GetString("ExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find path.
        /// </summary>
        public static string FindPath {
            get {
                return ResourceManager.GetString("FindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose graph assemble: .
        /// </summary>
        public static string GraphAssembleChoiceMsg {
            get {
                return ResourceManager.GetString("GraphAssembleChoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacle percent: {0} ({1}/{2}).
        /// </summary>
        public static string GraphFormat {
            get {
                return ResourceManager.GetString("GraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input height of graph: .
        /// </summary>
        public static string GraphHeightInputMsg {
            get {
                return ResourceManager.GetString("GraphHeightInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input width of graph: .
        /// </summary>
        public static string GraphWidthInputMsg {
            get {
                return ResourceManager.GetString("GraphWidthInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited: {0}.
        /// </summary>
        public static string InProcessStatisticsFormat {
            get {
                return ResourceManager.GetString("InProcessStatisticsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cost range.
        /// </summary>
        public static string InputCostRange {
            get {
                return ResourceManager.GetString("InputCostRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input graph parametres.
        /// </summary>
        public static string InputGraphParametres {
            get {
                return ResourceManager.GetString("InputGraphParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input obstacle percent.
        /// </summary>
        public static string InputObstaclePercent {
            get {
                return ResourceManager.GetString("InputObstaclePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input path: .
        /// </summary>
        public static string InputPathMsg {
            get {
                return ResourceManager.GetString("InputPathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input pipe name: .
        /// </summary>
        public static string InputPipeMsg {
            get {
                return ResourceManager.GetString("InputPipeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input server name: .
        /// </summary>
        public static string InputServerNameMsg {
            get {
                return ResourceManager.GetString("InputServerNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input level of smoothing: .
        /// </summary>
        public static string InputSmoothLevelMsg {
            get {
                return ResourceManager.GetString("InputSmoothLevelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input language: .
        /// </summary>
        public static string LanguageMsg {
            get {
                return ResourceManager.GetString("LanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthDimensionName {
            get {
                return ResourceManager.GetString("LengthDimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load graph.
        /// </summary>
        public static string LoadGraph {
            get {
                return ResourceManager.GetString("LoadGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose menu option: .
        /// </summary>
        public static string MenuOptionChoiceMsg {
            get {
                return ResourceManager.GetString("MenuOptionChoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input percent of obstacles: .
        /// </summary>
        public static string ObstaclePercentInputMsg {
            get {
                return ResourceManager.GetString("ObstaclePercentInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range. Try again: .
        /// </summary>
        public static string OutOfRangeMsg {
            get {
                return ResourceManager.GetString("OutOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding.
        /// </summary>
        public static string Pathfinding {
            get {
                return ResourceManager.GetString("Pathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding range.
        /// </summary>
        public static string PathfindingRange {
            get {
                return ResourceManager.GetString("PathfindingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps: {0}  Path cost: {1}  Visited: {2}.
        /// </summary>
        public static string PathfindingStatisticsFormat {
            get {
                return ResourceManager.GetString("PathfindingStatisticsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lower value of range: .
        /// </summary>
        public static string RangeLowerValueInputMsg {
            get {
                return ResourceManager.GetString("RangeLowerValueInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input upper value of range: .
        /// </summary>
        public static string RangeUpperValueInputMsg {
            get {
                return ResourceManager.GetString("RangeUpperValueInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve graph.
        /// </summary>
        public static string RecieveGraph {
            get {
                return ResourceManager.GetString("RecieveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize graph.
        /// </summary>
        public static string ResizeGraph {
            get {
                return ResourceManager.GetString("ResizeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse vertices.
        /// </summary>
        public static string ReverseVertices {
            get {
                return ResourceManager.GetString("ReverseVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save graph.
        /// </summary>
        public static string SaveGraph {
            get {
                return ResourceManager.GetString("SaveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send graph.
        /// </summary>
        public static string SendGraph {
            get {
                return ResourceManager.GetString("SendGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history.
        /// </summary>
        public static string ShowHistory {
            get {
                return ResourceManager.GetString("ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth graph.
        /// </summary>
        public static string SmoothGraph {
            get {
                return ResourceManager.GetString("SmoothGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose smooth level: .
        /// </summary>
        public static string SmoothLevelMsg {
            get {
                return ResourceManager.GetString("SmoothLevelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding visualization.
        /// </summary>
        public static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection....
        /// </summary>
        public static string WaitingForConnection {
            get {
                return ResourceManager.GetString("WaitingForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthDimensionName {
            get {
                return ResourceManager.GetString("WidthDimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
