//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinding.App.Console.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pathfinding.App.Console.Localization.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose algorithm: .
        /// </summary>
        public static string AlgorithmChoiceMsg {
            get {
                return ResourceManager.GetString("AlgorithmChoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply history.
        /// </summary>
        public static string ApplyHistory {
            get {
                return ResourceManager.GetString("ApplyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply history recording {0}?: .
        /// </summary>
        public static string ApplyHistoryMsg {
            get {
                return ResourceManager.GetString("ApplyHistoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply pathfinding statistics.
        /// </summary>
        public static string ApplyStatistics {
            get {
                return ResourceManager.GetString("ApplyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply statistics {0}?: .
        /// </summary>
        public static string ApplyStatisticsMsg {
            get {
                return ResourceManager.GetString("ApplyStatisticsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply pathfinding visualization.
        /// </summary>
        public static string ApplyVisualization {
            get {
                return ResourceManager.GetString("ApplyVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply visualization {0}?: .
        /// </summary>
        public static string ApplyVisualizationMsg {
            get {
                return ResourceManager.GetString("ApplyVisualizationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble graph.
        /// </summary>
        public static string AssembleGraph {
            get {
                return ResourceManager.GetString("AssembleGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad value input. Try again: .
        /// </summary>
        public static string BadInputMsg {
            get {
                return ResourceManager.GetString("BadInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change cost.
        /// </summary>
        public static string ChangeCost {
            get {
                return ResourceManager.GetString("ChangeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change graph colors.
        /// </summary>
        public static string ChangeGraphColors {
            get {
                return ResourceManager.GetString("ChangeGraphColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change path colors.
        /// </summary>
        public static string ChangePathColors {
            get {
                return ResourceManager.GetString("ChangePathColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change pathfinding colors.
        /// </summary>
        public static string ChangePathfindingColors {
            get {
                return ResourceManager.GetString("ChangePathfindingColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change range colors.
        /// </summary>
        public static string ChangeRangeColors {
            get {
                return ResourceManager.GetString("ChangeRangeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color: .
        /// </summary>
        public static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose graph.
        /// </summary>
        public static string ChooseGraph {
            get {
                return ResourceManager.GetString("ChooseGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Choose key to change: .
        /// </summary>
        public static string ChooseKeyMsg {
            get {
                return ResourceManager.GetString("ChooseKeyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear vertices colors.
        /// </summary>
        public static string ClearColors {
            get {
                return ResourceManager.GetString("ClearColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear graph.
        /// </summary>
        public static string ClearGraph {
            get {
                return ResourceManager.GetString("ClearGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear history.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear pathfinding range.
        /// </summary>
        public static string ClearPathfindingRange {
            get {
                return ResourceManager.GetString("ClearPathfindingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string ColorsUnitMenuItem {
            get {
                return ResourceManager.GetString("ColorsUnitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossed path color.
        /// </summary>
        public static string CrossedPathColor {
            get {
                return ResourceManager.GetString("CrossedPathColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomSmoothLevel {
            get {
                return ResourceManager.GetString("CustomSmoothLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark blue.
        /// </summary>
        public static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark cyan.
        /// </summary>
        public static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark gray.
        /// </summary>
        public static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark green.
        /// </summary>
        public static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark magenta.
        /// </summary>
        public static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark red.
        /// </summary>
        public static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark yellow.
        /// </summary>
        public static string DarkYellow {
            get {
                return ResourceManager.GetString("DarkYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease cost key.
        /// </summary>
        public static string DecreaseCost {
            get {
                return ResourceManager.GetString("DecreaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input animation speed delay time (milliseconds): .
        /// </summary>
        public static string DelayTimeInputMsg {
            get {
                return ResourceManager.GetString("DelayTimeInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor keys.
        /// </summary>
        public static string EditorKeys {
            get {
                return ResourceManager.GetString("EditorKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued color.
        /// </summary>
        public static string EnqueuedColor {
            get {
                return ResourceManager.GetString("EnqueuedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter animation delay.
        /// </summary>
        public static string EnterAnimationDelay {
            get {
                return ResourceManager.GetString("EnterAnimationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pathfinding range.
        /// </summary>
        public static string EnterPathfindingRange {
            get {
                return ResourceManager.GetString("EnterPathfindingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude from range key.
        /// </summary>
        public static string ExcludeFromRange {
            get {
                return ResourceManager.GetString("ExcludeFromRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit {0}?: .
        /// </summary>
        public static string ExitMsg {
            get {
                return ResourceManager.GetString("ExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find path.
        /// </summary>
        public static string FindPath {
            get {
                return ResourceManager.GetString("FindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacle percent: {0} ({1}/{2}).
        /// </summary>
        public static string GraphFormat {
            get {
                return ResourceManager.GetString("GraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input height of graph: .
        /// </summary>
        public static string GraphHeightInputMsg {
            get {
                return ResourceManager.GetString("GraphHeightInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input width of graph: .
        /// </summary>
        public static string GraphWidthInputMsg {
            get {
                return ResourceManager.GetString("GraphWidthInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in range key.
        /// </summary>
        public static string IncludeInRange {
            get {
                return ResourceManager.GetString("IncludeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase cost key.
        /// </summary>
        public static string IncreaseCost {
            get {
                return ResourceManager.GetString("IncreaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cost range.
        /// </summary>
        public static string InputCostRange {
            get {
                return ResourceManager.GetString("InputCostRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input graph parametres.
        /// </summary>
        public static string InputGraphParametres {
            get {
                return ResourceManager.GetString("InputGraphParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input host name: .
        /// </summary>
        public static string InputHostName {
            get {
                return ResourceManager.GetString("InputHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Input key on which you want to change it (Current: {1}): .
        /// </summary>
        public static string InputKeyMsg {
            get {
                return ResourceManager.GetString("InputKeyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input obstacle percent.
        /// </summary>
        public static string InputObstaclePercent {
            get {
                return ResourceManager.GetString("InputObstaclePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input path: .
        /// </summary>
        public static string InputPathMsg {
            get {
                return ResourceManager.GetString("InputPathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input port: .
        /// </summary>
        public static string InputPort {
            get {
                return ResourceManager.GetString("InputPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input server name: .
        /// </summary>
        public static string InputServerNameMsg {
            get {
                return ResourceManager.GetString("InputServerNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt algorithm key.
        /// </summary>
        public static string InterruptAlgorithm {
            get {
                return ResourceManager.GetString("InterruptAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string KeysUnit {
            get {
                return ResourceManager.GetString("KeysUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input language: .
        /// </summary>
        public static string LanguageMsg {
            get {
                return ResourceManager.GetString("LanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthDimensionName {
            get {
                return ResourceManager.GetString("LengthDimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load graph.
        /// </summary>
        public static string LoadGraph {
            get {
                return ResourceManager.GetString("LoadGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark to replace key.
        /// </summary>
        public static string MarkToReplace {
            get {
                return ResourceManager.GetString("MarkToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose menu option: .
        /// </summary>
        public static string MenuOptionChoiceMsg {
            get {
                return ResourceManager.GetString("MenuOptionChoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacle color.
        /// </summary>
        public static string ObstacleColor {
            get {
                return ResourceManager.GetString("ObstacleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input percent of obstacles: .
        /// </summary>
        public static string ObstaclePercentInputMsg {
            get {
                return ResourceManager.GetString("ObstaclePercentInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range. Try again: .
        /// </summary>
        public static string OutOfRangeMsg {
            get {
                return ResourceManager.GetString("OutOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path color.
        /// </summary>
        public static string PathColor {
            get {
                return ResourceManager.GetString("PathColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding.
        /// </summary>
        public static string Pathfinding {
            get {
                return ResourceManager.GetString("Pathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding control keys.
        /// </summary>
        public static string PathfindingControlKeys {
            get {
                return ResourceManager.GetString("PathfindingControlKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding range.
        /// </summary>
        public static string PathfindingRange {
            get {
                return ResourceManager.GetString("PathfindingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Steps: {1} Path cost: {2}.
        /// </summary>
        public static string PathfindingResultFormat {
            get {
                return ResourceManager.GetString("PathfindingResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause algorithm key.
        /// </summary>
        public static string PauseAlgorithm {
            get {
                return ResourceManager.GetString("PauseAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lower value of range: .
        /// </summary>
        public static string RangeLowerValueInputMsg {
            get {
                return ResourceManager.GetString("RangeLowerValueInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input upper value of range: .
        /// </summary>
        public static string RangeUpperValueInputMsg {
            get {
                return ResourceManager.GetString("RangeUpperValueInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve graph.
        /// </summary>
        public static string RecieveGraph {
            get {
                return ResourceManager.GetString("RecieveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular color.
        /// </summary>
        public static string RegularColor {
            get {
                return ResourceManager.GetString("RegularColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular keys.
        /// </summary>
        public static string RegularKeys {
            get {
                return ResourceManager.GetString("RegularKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace transit key.
        /// </summary>
        public static string ReplaceTransit {
            get {
                return ResourceManager.GetString("ReplaceTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset smooth key.
        /// </summary>
        public static string ResetSmooth {
            get {
                return ResourceManager.GetString("ResetSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize graph.
        /// </summary>
        public static string ResizeGraph {
            get {
                return ResourceManager.GetString("ResizeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume algorithm key.
        /// </summary>
        public static string ResumeAlgorithm {
            get {
                return ResourceManager.GetString("ResumeAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse vertex key.
        /// </summary>
        public static string ReverseVertex {
            get {
                return ResourceManager.GetString("ReverseVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse vertices.
        /// </summary>
        public static string ReverseVertices {
            get {
                return ResourceManager.GetString("ReverseVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save graph.
        /// </summary>
        public static string SaveGraph {
            get {
                return ResourceManager.GetString("SaveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send graph.
        /// </summary>
        public static string SendGraph {
            get {
                return ResourceManager.GetString("SendGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history.
        /// </summary>
        public static string ShowHistory {
            get {
                return ResourceManager.GetString("ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth graph key.
        /// </summary>
        public static string SmoothGraph {
            get {
                return ResourceManager.GetString("SmoothGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth graph.
        /// </summary>
        public static string SmoothGraphItem {
            get {
                return ResourceManager.GetString("SmoothGraphItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source color.
        /// </summary>
        public static string SourceColor {
            get {
                return ResourceManager.GetString("SourceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding speed down key.
        /// </summary>
        public static string SpeedDown {
            get {
                return ResourceManager.GetString("SpeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding speed up key.
        /// </summary>
        public static string SpeedUp {
            get {
                return ResourceManager.GetString("SpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  Time: {1}     Visited: {2}.
        /// </summary>
        public static string StatisticsFormat {
            get {
                return ResourceManager.GetString("StatisticsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step by step pathfinding key.
        /// </summary>
        public static string StepByStepPathfinding {
            get {
                return ResourceManager.GetString("StepByStepPathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit smooth key.
        /// </summary>
        public static string SubmitSmooth {
            get {
                return ResourceManager.GetString("SubmitSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target color.
        /// </summary>
        public static string TargetColor {
            get {
                return ResourceManager.GetString("TargetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit color.
        /// </summary>
        public static string TransitColor {
            get {
                return ResourceManager.GetString("TransitColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit keys.
        /// </summary>
        public static string TransitKeys {
            get {
                return ResourceManager.GetString("TransitKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo smooth key.
        /// </summary>
        public static string UndoSmooth {
            get {
                return ResourceManager.GetString("UndoSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex down key.
        /// </summary>
        public static string VertexDown {
            get {
                return ResourceManager.GetString("VertexDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex left key.
        /// </summary>
        public static string VertexLeft {
            get {
                return ResourceManager.GetString("VertexLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex right key.
        /// </summary>
        public static string VertexRight {
            get {
                return ResourceManager.GetString("VertexRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex up key.
        /// </summary>
        public static string VertexUp {
            get {
                return ResourceManager.GetString("VertexUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited color.
        /// </summary>
        public static string VisitedColor {
            get {
                return ResourceManager.GetString("VisitedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding visualization.
        /// </summary>
        public static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection....
        /// </summary>
        public static string WaitingForConnection {
            get {
                return ResourceManager.GetString("WaitingForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthDimensionName {
            get {
                return ResourceManager.GetString("WidthDimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
