//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleVersion.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleVersion.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose algorithm: .
        /// </summary>
        internal static string ChooseAlrorithm {
            get {
                return ResourceManager.GetString("ChooseAlrorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose graph assemble: .
        /// </summary>
        internal static string ChooseGraphAssemble {
            get {
                return ResourceManager.GetString("ChooseGraphAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose vertex to reverse: .
        /// </summary>
        internal static string ChooseVertexToReverseMsg {
            get {
                return ResourceManager.GetString("ChooseVertexToReverseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter delay time: .
        /// </summary>
        internal static string DelayTimeInputMsg {
            get {
                return ResourceManager.GetString("DelayTimeInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point: .
        /// </summary>
        internal static string EndVertexCoordinateInputMsg {
            get {
                return ResourceManager.GetString("EndVertexCoordinateInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit app &lt;1 - yes/0 - no&gt;?: .
        /// </summary>
        internal static string ExitAppMsg {
            get {
                return ResourceManager.GetString("ExitAppMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter height of graph: .
        /// </summary>
        internal static string HeightInputMsg {
            get {
                return ResourceManager.GetString("HeightInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter lower vertices cost value: .
        /// </summary>
        internal static string LowerValueOfRangeMsg {
            get {
                return ResourceManager.GetString("LowerValueOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter percent of obstacles: .
        /// </summary>
        internal static string ObstaclePercentInputMsg {
            get {
                return ResourceManager.GetString("ObstaclePercentInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose option: .
        /// </summary>
        internal static string OptionInputMsg {
            get {
                return ResourceManager.GetString("OptionInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point: .
        /// </summary>
        internal static string StartVertexPointInputMsg {
            get {
                return ResourceManager.GetString("StartVertexPointInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to load saved graph.
        /// </summary>
        internal static string TryToLoadSavedGraph {
            get {
                return ResourceManager.GetString("TryToLoadSavedGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter upper vertices cost value: .
        /// </summary>
        internal static string UpperValueOfRangeMsg {
            get {
                return ResourceManager.GetString("UpperValueOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new top value: .
        /// </summary>
        internal static string VertexCostInputMsg {
            get {
                return ResourceManager.GetString("VertexCostInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter width of graph: .
        /// </summary>
        internal static string WidthInputMsg {
            get {
                return ResourceManager.GetString("WidthInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter x coordinate of point: .
        /// </summary>
        internal static string XCoordinateInputMsg {
            get {
                return ResourceManager.GetString("XCoordinateInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter y coordinate of point: .
        /// </summary>
        internal static string YCoordinateInputMsg {
            get {
                return ResourceManager.GetString("YCoordinateInputMsg", resourceCulture);
            }
        }
    }
}
