//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleVersion.Resource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleVersion.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose algorithm: .
        /// </summary>
        internal static string ChooseAlrorithm {
            get {
                return ResourceManager.GetString("ChooseAlrorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose graph assemble: .
        /// </summary>
        internal static string ChooseGraphAssemble {
            get {
                return ResourceManager.GetString("ChooseGraphAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose vertex to reverse: .
        /// </summary>
        internal static string ChooseVertexToReverseMsg {
            get {
                return ResourceManager.GetString("ChooseVertexToReverseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter delay time: .
        /// </summary>
        internal static string DelayTimeInputMsg {
            get {
                return ResourceManager.GetString("DelayTimeInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End point: .
        /// </summary>
        internal static string EndVertexCoordinateInputMsg {
            get {
                return ResourceManager.GetString("EndVertexCoordinateInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit app &lt;1 - yes/0 - no&gt;?: .
        /// </summary>
        internal static string ExitAppMsg {
            get {
                return ResourceManager.GetString("ExitAppMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter height of graph: .
        /// </summary>
        internal static string HeightInputMsg {
            get {
                return ResourceManager.GetString("HeightInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter lower vertices cost value: .
        /// </summary>
        internal static string LowerValueOfRangeMsg {
            get {
                return ResourceManager.GetString("LowerValueOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter percent of obstacles: .
        /// </summary>
        internal static string ObstaclePercentInputMsg {
            get {
                return ResourceManager.GetString("ObstaclePercentInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose option: .
        /// </summary>
        internal static string OptionInputMsg {
            get {
                return ResourceManager.GetString("OptionInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start point: .
        /// </summary>
        internal static string StartVertexPointInputMsg {
            get {
                return ResourceManager.GetString("StartVertexPointInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter upper vertices cost value: .
        /// </summary>
        internal static string UpperValueOfRangeMsg {
            get {
                return ResourceManager.GetString("UpperValueOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new top value: .
        /// </summary>
        internal static string VertexCostInputMsg {
            get {
                return ResourceManager.GetString("VertexCostInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply visualization? &lt;1 - yes/0 - no&gt;: .
        /// </summary>
        internal static string VisualizationMsg {
            get {
                return ResourceManager.GetString("VisualizationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter width of graph: .
        /// </summary>
        internal static string WidthInputMsg {
            get {
                return ResourceManager.GetString("WidthInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter x coordinate of point: .
        /// </summary>
        internal static string XCoordinateInputMsg {
            get {
                return ResourceManager.GetString("XCoordinateInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter y coordinate of point: .
        /// </summary>
        internal static string YCoordinateInputMsg {
            get {
                return ResourceManager.GetString("YCoordinateInputMsg", resourceCulture);
            }
        }
    }
}
