//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinding.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pathfinding.ConsoleApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithms.
        /// </summary>
        internal static string Algorithms {
            get {
                return ResourceManager.GetString("Algorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A*.
        /// </summary>
        internal static string AStar {
            get {
                return ResourceManager.GetString("AStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A* greedy.
        /// </summary>
        internal static string AStarGreedy {
            get {
                return ResourceManager.GetString("AStarGreedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A* Lee.
        /// </summary>
        internal static string AStarLee {
            get {
                return ResourceManager.GetString("AStarLee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidirect A*.
        /// </summary>
        internal static string BidirectAStar {
            get {
                return ResourceManager.GetString("BidirectAStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi Dijkstra.
        /// </summary>
        internal static string BidirectDijkstra {
            get {
                return ResourceManager.GetString("BidirectDijkstra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidirect Lee.
        /// </summary>
        internal static string BidirectLee {
            get {
                return ResourceManager.GetString("BidirectLee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chebyshev.
        /// </summary>
        internal static string Chebyshev {
            get {
                return ResourceManager.GetString("Chebyshev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseAlgorithms {
            get {
                return ResourceManager.GetString("CloseAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine.
        /// </summary>
        internal static string Cosine {
            get {
                return ResourceManager.GetString("Cosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFS cost.
        /// </summary>
        internal static string CostGreedy {
            get {
                return ResourceManager.GetString("CostGreedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteGraph {
            get {
                return ResourceManager.GetString("DeleteGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFS.
        /// </summary>
        internal static string DepthFirst {
            get {
                return ResourceManager.GetString("DepthFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal.
        /// </summary>
        internal static string Diagonal {
            get {
                return ResourceManager.GetString("Diagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijkstra.
        /// </summary>
        internal static string Dijkstra {
            get {
                return ResourceManager.GetString("Dijkstra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFS dist.
        /// </summary>
        internal static string DistanceFirst {
            get {
                return ResourceManager.GetString("DistanceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        internal static string Editable {
            get {
                return ResourceManager.GetString("Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euclidian.
        /// </summary>
        internal static string Euclidian {
            get {
                return ResourceManager.GetString("Euclidian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph only.
        /// </summary>
        internal static string GraphOnly {
            get {
                return ResourceManager.GetString("GraphOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid export option.
        /// </summary>
        internal static string InvalidExportOptions {
            get {
                return ResourceManager.GetString("InvalidExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lee.
        /// </summary>
        internal static string Lee {
            get {
                return ResourceManager.GetString("Lee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manhattan.
        /// </summary>
        internal static string Manhattan {
            get {
                return ResourceManager.GetString("Manhattan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moore.
        /// </summary>
        internal static string Moore {
            get {
                return ResourceManager.GetString("Moore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly.
        /// </summary>
        internal static string Readonly {
            get {
                return ResourceManager.GetString("Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run field.
        /// </summary>
        internal static string RunField {
            get {
                return ResourceManager.GetString("RunField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snake.
        /// </summary>
        internal static string Snake {
            get {
                return ResourceManager.GetString("Snake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateAlgorithms {
            get {
                return ResourceManager.GetString("UpdateAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neumann.
        /// </summary>
        internal static string VonNeumann {
            get {
                return ResourceManager.GetString("VonNeumann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was saved.
        /// </summary>
        internal static string WasDeletedMsg {
            get {
                return ResourceManager.GetString("WasDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was loaded.
        /// </summary>
        internal static string WasLoadedMsg {
            get {
                return ResourceManager.GetString("WasLoadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs were saved.
        /// </summary>
        internal static string WereDeletedMsg {
            get {
                return ResourceManager.GetString("WereDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs were loaded.
        /// </summary>
        internal static string WereLoadedMsg {
            get {
                return ResourceManager.GetString("WereLoadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With range.
        /// </summary>
        internal static string WithRange {
            get {
                return ResourceManager.GetString("WithRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With runs.
        /// </summary>
        internal static string WithRuns {
            get {
                return ResourceManager.GetString("WithRuns", resourceCulture);
            }
        }
    }
}
