//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinding.App.Console.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Colours : global::System.Configuration.ApplicationSettingsBase {
        
        private static Colours defaultInstance = ((Colours)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Colours())));
        
        public static Colours Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.ConsoleColor ObstacleColor {
            get {
                return ((global::System.ConsoleColor)(this["ObstacleColor"]));
            }
            set {
                this["ObstacleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.ConsoleColor RegularColor {
            get {
                return ((global::System.ConsoleColor)(this["RegularColor"]));
            }
            set {
                this["RegularColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.ConsoleColor VisitedColor {
            get {
                return ((global::System.ConsoleColor)(this["VisitedColor"]));
            }
            set {
                this["VisitedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.ConsoleColor EnqueuedColor {
            get {
                return ((global::System.ConsoleColor)(this["EnqueuedColor"]));
            }
            set {
                this["EnqueuedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkYellow")]
        public global::System.ConsoleColor PathColor {
            get {
                return ((global::System.ConsoleColor)(this["PathColor"]));
            }
            set {
                this["PathColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.ConsoleColor CrossedPathColor {
            get {
                return ((global::System.ConsoleColor)(this["CrossedPathColor"]));
            }
            set {
                this["CrossedPathColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.ConsoleColor SourceColor {
            get {
                return ((global::System.ConsoleColor)(this["SourceColor"]));
            }
            set {
                this["SourceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.ConsoleColor TargetColor {
            get {
                return ((global::System.ConsoleColor)(this["TargetColor"]));
            }
            set {
                this["TargetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.ConsoleColor TransitColor {
            get {
                return ((global::System.ConsoleColor)(this["TransitColor"]));
            }
            set {
                this["TransitColor"] = value;
            }
        }
    }
}
