//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinding.App.Console.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Keys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Keys defaultInstance = ((Keys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Keys())));
        
        public static Keys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.ConsoleKey VertexUp {
            get {
                return ((global::System.ConsoleKey)(this["VertexUp"]));
            }
            set {
                this["VertexUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.ConsoleKey VertexDown {
            get {
                return ((global::System.ConsoleKey)(this["VertexDown"]));
            }
            set {
                this["VertexDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.ConsoleKey VertexLeft {
            get {
                return ((global::System.ConsoleKey)(this["VertexLeft"]));
            }
            set {
                this["VertexLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.ConsoleKey VertexRight {
            get {
                return ((global::System.ConsoleKey)(this["VertexRight"]));
            }
            set {
                this["VertexRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::System.ConsoleKey IncludeInRange {
            get {
                return ((global::System.ConsoleKey)(this["IncludeInRange"]));
            }
            set {
                this["IncludeInRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public global::System.ConsoleKey ExcludeFromRange {
            get {
                return ((global::System.ConsoleKey)(this["ExcludeFromRange"]));
            }
            set {
                this["ExcludeFromRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::System.ConsoleKey ReverseVertex {
            get {
                return ((global::System.ConsoleKey)(this["ReverseVertex"]));
            }
            set {
                this["ReverseVertex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpArrow")]
        public global::System.ConsoleKey IncreaseCost {
            get {
                return ((global::System.ConsoleKey)(this["IncreaseCost"]));
            }
            set {
                this["IncreaseCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DownArrow")]
        public global::System.ConsoleKey DecreaseCost {
            get {
                return ((global::System.ConsoleKey)(this["DecreaseCost"]));
            }
            set {
                this["DecreaseCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::System.ConsoleKey ReplaceTransit {
            get {
                return ((global::System.ConsoleKey)(this["ReplaceTransit"]));
            }
            set {
                this["ReplaceTransit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public global::System.ConsoleKey MarkToReplace {
            get {
                return ((global::System.ConsoleKey)(this["MarkToReplace"]));
            }
            set {
                this["MarkToReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpArrow")]
        public global::System.ConsoleKey SpeedUp {
            get {
                return ((global::System.ConsoleKey)(this["SpeedUp"]));
            }
            set {
                this["SpeedUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DownArrow")]
        public global::System.ConsoleKey SpeedDown {
            get {
                return ((global::System.ConsoleKey)(this["SpeedDown"]));
            }
            set {
                this["SpeedDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::System.ConsoleKey ResumeAlgorithm {
            get {
                return ((global::System.ConsoleKey)(this["ResumeAlgorithm"]));
            }
            set {
                this["ResumeAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::System.ConsoleKey PauseAlgorithm {
            get {
                return ((global::System.ConsoleKey)(this["PauseAlgorithm"]));
            }
            set {
                this["PauseAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::System.ConsoleKey InterruptAlgorithm {
            get {
                return ((global::System.ConsoleKey)(this["InterruptAlgorithm"]));
            }
            set {
                this["InterruptAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.ConsoleKey StepByStepPathfinding {
            get {
                return ((global::System.ConsoleKey)(this["StepByStepPathfinding"]));
            }
            set {
                this["StepByStepPathfinding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.ConsoleKey SmoothGraph {
            get {
                return ((global::System.ConsoleKey)(this["SmoothGraph"]));
            }
            set {
                this["SmoothGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.ConsoleKey UndoSmooth {
            get {
                return ((global::System.ConsoleKey)(this["UndoSmooth"]));
            }
            set {
                this["UndoSmooth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::System.ConsoleKey ResetSmooth {
            get {
                return ((global::System.ConsoleKey)(this["ResetSmooth"]));
            }
            set {
                this["ResetSmooth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::System.ConsoleKey SubmitSmooth {
            get {
                return ((global::System.ConsoleKey)(this["SubmitSmooth"]));
            }
            set {
                this["SubmitSmooth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::System.ConsoleKey NeighbourhoodAction {
            get {
                return ((global::System.ConsoleKey)(this["NeighbourhoodAction"]));
            }
            set {
                this["NeighbourhoodAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spacebar")]
        public global::System.ConsoleKey ExitVertexAction {
            get {
                return ((global::System.ConsoleKey)(this["ExitVertexAction"]));
            }
            set {
                this["ExitVertexAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::System.ConsoleKey ResetSwitching {
            get {
                return ((global::System.ConsoleKey)(this["ResetSwitching"]));
            }
            set {
                this["ResetSwitching"] = value;
            }
        }
    }
}
